### ISSUE TITLE
How to custimize types.json in tools like polkadot-js-api

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-proof-tools#9]
```
promote:~ denny$ polkadot-js-api query.system.account --ws ws://127.0.0.1:9944
Unable to resolve type RingBalance, it will fail on constrution
Unable to resolve type EthTransactionIndex, it will fail on constrution
Unable to resolve type KtonBalance, it will fail on constrution
Unable to resolve type DepositId, it will fail on constrution
Unable to resolve type EthHeader, it will fail on constrution
Unable to resolve type Receipt, it will fail on constrution
Unable to resolve type EthReceiptProof, it will fail on constrution
Unable to resolve type MomentT, it will fail on constrution
Unknown types found, no types for DepositId,EthAddress,EthHeader,EthReceiptProof,EthTransactionIndex,HeaderInfo,KtonBalance,MomentT,Power,RKT,Receipt,RingBalance,StakingBalanceT,StakingLedgerT,ValidatorReward
2020-03-06 14:51:00        API/INIT: Error: FATAL: Unable to initialize the API: createType(EthTransactionIndex):: Cannot construct unknown type EthTransactionIndex
    at EventEmitter.value (/Users/denny/.config/yarn/global/node_modules/@polkadot/api/base/Init.js:67:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: FATAL: Unable to initialize the API: createType(EthTransactionIndex):: Cannot construct unknown type EthTransactionIndex
    at EventEmitter.value (/Users/denny/.config/yarn/global/node_modules/@polkadot/api/base/Init.js:67:25)
```

**Comment by HackFisher** [comment]
https://github.com/polkadot-js/tools/tree/master/packages/api-cli

**Comment by clearloop** [comment]
I suggest we register a bot account with a pretty girl avatar like @rust-highfive, and powered her by [ansible][ansible] or [jenkins][jenkins]. (or any other handwrite tools)

Listen to the update of [darwinia][darwinia], if `types.json` changes @darwinia-highfive will re-write `darwinia-offchain-tools` immediately.

[ansible]: https://github.com/ansible/ansible
[darwinia]: https://github.com/darwinia-network/darwinia
[jenkins]: https://github.com/jenkinsci/jenkins
